version: "3.8"

services:
  uploads-api:
    container_name: uploads-api
    build: .
    environment:
      # Change to development to watch for changes.
      - ENVIRONMENT=production
    volumes:
      - /usr/app
      - type: bind
        source: ./uploads
        target: /usr/uploads
      - type: bind
        source: ./auth.json
        target: /auth.json
      - type: bind
        source: ./env.jsonc
        target: /env.jsonc
    ports:
      - "4749:8000"
    restart: always
